# Pull request validation pipeline config

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  buildPlatform: 'x86|x64|ARM'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet Tool'

- task: NuGetCommand@2
  displayName: 'Restore Solution'
  inputs:
    restoreSolution: '**/*.sln'

- task: ResharperCli@2
  displayName: 'RESharper CLI Code Analyzer'
  enabled: false
  inputs:
    solutionOrProjectPath: 'GUT.Schedule/GUTSchedule.sln'
    failBuildLevelSelector: 'Error'
    failBuildOnCodeIssues: false

- task: XamarinAndroid@1
  displayName: 'Build Android'
  enabled: false
  inputs:
    projectFile: '**/**.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildVersionOption: 'latest'
    msbuildArchitectureOption: 'x64'
    jdkOption: 'JDKVersion'

- task: DownloadSecureFile@1
  name: cert
  displayName: 'Download PFX certificate'
  inputs:
    secureFile: 'GUTScheduleCert.pfx'

- task: CopyFiles@2
  displayName: 'Copy PFX certificate to work folder'
  inputs:
    Contents: '$(cert.secureFilePath)'
    TargetFolder: '$(Build.Repository.LocalPath)/GUTSchedule/GUTSchedule.UWP'

- task: VSBuild@1
  displayName: 'Build UWP'
  inputs:
    platform: 'x64'
    solution: '**/**.UWP.csproj'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxPackageSigningEnabled=false'